CREATE TABLE [dbo].[THANHPHO](
	[ID]				[int] IDENTITY(1,1) NOT NULL,
	[MA_THANHPHO]		[nvarchar](5) NULL,
	[TEN_THANHPHO]		[nvarchar](50) NULL
);

CREATE TABLE [dbo].[NGANHNGHE_KINHTE_CAP01](
	[ID]							[int] IDENTITY(1,1) NOT NULL,
	[MA_NGANHNGHE_KINHTE_CAP01]		[nvarchar](5) NULL,
	[TEN_NGANHNGHE_KINHTE_CAP01]	[nvarchar](500) NULL
);

CREATE TABLE [dbo].[NGANHNGHE_KINHTE_CAP02](
	[ID]							[int] IDENTITY(1,1) NOT NULL,
	[MA_NGANHNGHE_KINHTE_CAP01]		[nvarchar](5) NULL,
	[MA_NGANHNGHE_KINHTE_CAP02]		[nvarchar](5) NULL,
	[TEN_NGANHNGHE_KINHTE_CAP02]	[nvarchar](500) NULL
);

CREATE TABLE [dbo].[NGANHNGHE_KINHTE_CAP03](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MA_NGANHNGHE_KINHTE_CAP01]		[nvarchar](5) NULL,
	[MA_NGANHNGHE_KINHTE_CAP02]		[nvarchar](5) NULL,
	[MA_NGANHNGHE_KINHTE_CAP03]		[nvarchar](5) NULL,
	[TEN_NGANHNGHE_KINHTE_CAP03]	[nvarchar](500) NULL
);

CREATE TABLE [dbo].[LOAIHINH_DOANHNGHIEP](
	[ID]							[int] IDENTITY(1,1) NOT NULL,
	[MA_LOAIHINH_DOANHNGHIEP]		[nvarchar](5) NULL,
	[TEN_LOAIHINH_DOANHNGHIEP]		[nvarchar](500) NULL,
);

CREATE TABLE [dbo].[CHINHANH](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MA_CHINHANH] [nvarchar](20) NULL,
	[TEN_CHINHANH] [nvarchar](500) NULL,
	[DIACHI_CHINHANH] [nvarchar](max) NULL,
	[MA_THANHPHO] [int] NULL,
	[MA_KHUVUC] [nvarchar](10) NULL
);

CREATE TABLE [dbo].[KHUVUC](
	[ID]			[int] IDENTITY(1,1) NOT NULL,
	[MA_KHUVUC]		[nvarchar](10) NULL,
	[TEN_KHUVUC]	[nvarchar](50) NULL
);

CREATE TABLE [dbo].[LOAI_GIAYTO](
	[ID]				[int] IDENTITY(1,1) NOT NULL,
	[MA_LOAI_GIAYTO]	[nvarchar](10) NULL,
	[TEN_LOAI_GIAYTO]	[nvarchar](50) NULL
);

CREATE TABLE [dbo].[KHACHHANG](
	[ID]					[int] IDENTITY(1,1) NOT NULL,
	[MA_CHINHANH]			[nvarchar](10) NULL,
	[MA_CIC]				[nvarchar](20) NULL,
	[MA_KHACHHANG]			[nvarchar](12) NULL,
	[TEN_KHACHHANG]			[nvarchar](500) NULL,
	[NGAY_MO_TAIKHOAN]		[date] NULL,
	[NGAY_SINH]				[date] NULL,
	[MA_GIAYTO]				[nvarchar](20) NULL,
	[MA_LOAI_KHACHHANG]		[nvarchar](10) NULL,
	[MA_LOAI_GIAYTO]		[nvarchar](5) NULL,
	[NGAYCAP_GIAYTO]		[date] NULL,
	[MA_NOICAP]				[int] NULL,
	[DIACHI]				[nvarchar](max) NULL,
	[NGAY_THANHLAP]			[date] NULL,
	[QUY_MO_DOANHNGHIEP]	[int] NULL,
	[VON_DIEULE]			[numeric]	(18,0)	NULL,
	[MA_TAIKHOAN_THANHTOAN]	[nvarchar](20) NULL,
	[TEN_CHU_DOANHNGHIEP]	[nvarchar](500) NULL,
	[ID_CHU_DOANHNGHIEP]	[nvarchar](50) NULL,
	[MA_LOAIHINH_KHACHHANG]	[nvarchar](5) NULL,
	[MA_NGANHNGHE_KINHTE]	[nvarchar](5) NULL
);

CREATE TABLE TIENGUI_TIETKIEM
(
ID						INT				IDENTITY(1,1),
MA_KHACHHANG			NVARCHAR(20),
MA_TAIKHOAN_TIETKIEM	NVARCHAR(20),
NGAY_GUI				DATE,
NGAY_DENHAN				DATE,
KY_HAN					INT,
LAISUAT					NUMERIC(7,2),
SOTIEN					NUMERIC(18,2),
LOAITIEN				NVARCHAR(5),
SOTIEN_LAI				NUMERIC(18,2),
SOTIEN_THUCNHAN			NUMERIC(18,2),
TUGIAHAN				INT,
NGAY_RUT				DATE,
TRANG_THAI				INT
);

CREATE TABLE TIENGUI_COKYHAN
(
ID						INT				IDENTITY(1,1),
MA_KHACHHANG			NVARCHAR(20),
MA_TAIKHOAN_TGCKH		NVARCHAR(20),
NGAY_GUI				DATE,
NGAY_DENHAN				DATE,
KY_HAN					INT,
LAISUAT					NUMERIC(7,2),
SOTIEN					NUMERIC(18,2),
LOAITIEN				NVARCHAR(5),
SOTIEN_LAI				NUMERIC(18,2),
SOTIEN_THUCNHAN			NUMERIC(18,2),
TUGIAHAN				INT,
NGAY_RUT				DATE,
TRANG_THAI				INT
);

CREATE TABLE TIENGUI_THANHTOAN(
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MA_TAIKHOAN_THANHTOAN] [nvarchar](15) NULL,
	[THOIGIAN_GIAODICH] [datetime] NULL,
	[SODU_BANDAU] [numeric](18, 0) NULL,
	[SOTIEN_TANG] [numeric](18, 0) NULL,
	[SOTIEN_GIAM] [numeric](18, 0) NULL,
	[SODU_CUOI] [numeric](18, 0) NULL,
	[LOAI_TIEN] [nvarchar](5) NULL,
	[GHI_CHU] [nvarchar](max) NULL,
	[TAIKHOAN_GUITIEN] [nvarchar](50) NULL,
	[TAIKHOAN_NHANTIEN] [nvarchar](50) NULL,
	[LOAI_CK] [nvarchar](5) NULL
	);

CREATE TABLE HOPDONG_TINDUNG
(
ID					INT				IDENTITY(1,1),
MA_KHACHHANG		NVARCHAR(20),
MA_HOPDONG_TINDUNG	NVARCHAR(20),
MA_HOPDONG_THECHAP	NVARCHAR(20),
SO_HOPDONG_TINDUNG	NVARCHAR(500),
MA_MUCDICH_CAPTD	NVARCHAR(15),
MA_HINHTHUC_CAPTD		NVARCHAR(15),
MA_PHUONGTHUC_CHOVAY	NVARCHAR(15),
NGAY_GIAINGAN			DATE,
SOTIEN					NUMERIC(18,2),
LOAI_TIEN				NVARCHAR(10),
NGAY_DAOHAN				DATE,
KY_HAN				INT,
LAISUAT				NUMERIC(10,2)
);

CREATE TABLE HOPDONG_THECHAP
(
ID						INT IDENTITY(1,1),
MA_HOPDONG_THECHAP		NVARCHAR(20),	
TEN_HOPDONG_THECHAP		NVARCHAR(MAX),
NGAY_HOPDONG_THECHAP	DATE,
GHI_CHU					NVARCHAR(MAX)
);

CREATE TABLE MUCDICH_CAPTINDUNG
(
MA_CAP1				NVARCHAR(15),
TEN_MUCDICH_CAP1	NVARCHAR(500),
MA_CAP2				NVARCHAR(15),
TEN_MUCDICH_CAP2	NVARCHAR(500),
MA_CAP3				NVARCHAR(15),
TEN_MUCDICH_CAP3	NVARCHAR(500),
MA_CAP4				NVARCHAR(15),
TEN_MUCDICH_CAP4	NVARCHAR(500),
MA_CAP5				NVARCHAR(15),
TEN_MUCDICH_CAP5	NVARCHAR(500),
MA_MUCDICH_CAPTD	NVARCHAR(15)
);

CREATE TABLE HINHTHUC_CAPTINDUNG
(
MA_CAP1				NVARCHAR(15),
TEN_HINHTHUC_CAP1	NVARCHAR(500),
MA_CAP2				NVARCHAR(15),
TEN_HINHTHUC_CAP2	NVARCHAR(500),
MA_HINHTHUC_CAPTD	NVARCHAR(15)
);

CREATE TABLE PHUONGTHUC_CHOVAY
(
MA_CAP1					NVARCHAR(15),
TEN_PHUONGTHUC_CAP1		NVARCHAR(500),
MA_CAP2					NVARCHAR(15),
TEN_PHUONGTHUC_CAP2		NVARCHAR(500),
MA_PHUONGTHUC_CHOVAY	NVARCHAR(15)
);

CREATE TABLE LOAIHINH_TSBD
(
MA_CAP1				NVARCHAR(15),
TEN_LOAIHINH_CAP1	NVARCHAR(500),
MA_CAP2				NVARCHAR(15),
TEN_LOAIHINH_CAP2	NVARCHAR(500),
MA_CAP3				NVARCHAR(15),
TEN_LOAIHINH_CAP3	NVARCHAR(500),
MA_CAP4				NVARCHAR(15),
TEN_LOAIHINH_CAP4	NVARCHAR(500),
MA_LOAIHINH_TSBD	NVARCHAR(15)
);

CREATE TABLE TAISAN_BAODAM
(	ID					INT IDENTITY(1,1),
	MA_TAISAN_BAODAM	NVARCHAR(20),	
	MA_LOAIHINH_TSBD	nvarchar(15),
	GIATRI				NUMERIC(18,2),
	DIACHI				NVARCHAR(MAX),
	MA_THANH_PHO		NVARCHAR(5),
	MA_HOPDONG_THECHAP	NVARCHAR(20),
	GHICHU				NVARCHAR(MAX)
);

CREATE TABLE KHACHHANG_TRANO
(
ID					INT				IDENTITY(1,1),
MA_HOPDONG_TINDUNG	NVARCHAR(20),
KYTRA				INT,
NGAYTRA				DATE,
SOTIEN_LAI			NUMERIC(18,2),
TONG_TIEN			NUMERIC(18,2)
);

CREATE TABLE KHACHHANG_TRANO
(
ID					INT				IDENTITY(1,1),
MA_HOPDONG_TINDUNG	NVARCHAR(20),
KYTRA				INT,
NGAYTRA				DATE,
SOTIEN_LAI			NUMERIC(18,2),
TONG_TIEN			NUMERIC(18,2)
);
