--- PROC 1: PROC XOAY VÒNG KỲ HẠN ĐỐI VỚI TRƯỜNG HỢP TỰ ĐỘNG GIA HẠN
CREATE PROC XOAYVONG2
@MA_TAIKHOAN		NVARCHAR(20)
AS
BEGIN
	--> KHAI BÁO BIẾN

	DECLARE @NGAYDENHAN AS DATE;
	DECLARE	@NGAYRUT	AS DATE;
	DECLARE @KYHAN		AS INT;

	SET @NGAYDENHAN	= (SELECT NGAY_DENHAN	FROM TIENGUI_TIETKIEM WHERE MA_TAIKHOAN_TIETKIEM = @MA_TAIKHOAN);
	SET @NGAYRUT	= (SELECT NGAY_RUT		FROM TIENGUI_TIETKIEM WHERE MA_TAIKHOAN_TIETKIEM = @MA_TAIKHOAN);
	SET @KYHAN		= (SELECT KY_HAN		FROM TIENGUI_TIETKIEM WHERE MA_TAIKHOAN_TIETKIEM = @MA_TAIKHOAN);
	
	--> CHẠY VÒNG LẶP
	while @NGAYDENHAN < @NGAYRUT
		BEGIN
			UPDATE	TIENGUI_TIETKIEM
			SET		SOTIEN	=	SOTIEN + ( DATEDIFF(D, NGAY_GUI, NGAY_DENHAN)*LAISUAT*SOTIEN )/(100*365), --> CẬP NHẬT LẠI GỐC MỚI = GỐC + LÃI
								NGAY_GUI	=	@NGAYDENHAN, --> ĐẦU KỲ MỚI BẰNG CUỐI KỲ CŨ
								NGAY_DENHAN	=	DATEADD(MONTH, @KYHAN ,NGAY_DENHAN)
			WHERE	MA_TAIKHOAN_TIETKIEM = @MA_TAIKHOAN
			SET @NGAYDENHAN = (SELECT NGAY_DENHAN FROM TIENGUI_TIETKIEM WHERE MA_TAIKHOAN_TIETKIEM = @MA_TAIKHOAN)
		END
END;

--- PROC 2: TÍNH TIỀN LÃI TIỀN GỬI TIẾT KIỆM CỦA KHÁCH HÀNG
ALTER PROCEDURE TINHLAI_TIENGUI_TIETKIEM
AS
BEGIN
    -- Khai báo CURSOR cho danh sách tất cả các tài khoản cần xử lý
    DECLARE @MA_TAIKHOAN NVARCHAR(20);
    
    DECLARE CURSOR_TAIKHOAN CURSOR FOR
    SELECT MA_TAIKHOAN_TIETKIEM FROM TIENGUI_TIETKIEM;

    -- Mở CURSOR
    OPEN CURSOR_TAIKHOAN;
    
    -- Lấy từng tài khoản trong CURSOR
    FETCH NEXT FROM CURSOR_TAIKHOAN INTO @MA_TAIKHOAN;

    -- Bắt đầu vòng lặp CURSOR
    WHILE @@FETCH_STATUS = 0
    BEGIN
        -- CẬP NHẬT NGÀY RÚT THEO NGÀY LÀM VIỆC GẦN NHẤT
        UPDATE TIENGUI_TIETKIEM
        SET NGAY_RUT = NGAY_LAMVIEC_GANNHAT
        FROM TIENGUI_TIETKIEM A
            INNER JOIN NGAY_LAMVIEC B ON A.NGAY_RUT = B.NGAY_DENHAN
        WHERE A.TRANG_THAI = 1
            AND NGAY_RUT >= A.NGAY_DENHAN
            AND A.MA_TAIKHOAN_TIETKIEM = @MA_TAIKHOAN;

        -- Khai báo các biến
        DECLARE @NGAYGUI AS DATE;
        DECLARE @NGAYDENHAN AS DATE;
        DECLARE @TUGIAHAN AS INT;
        DECLARE @NGAYRUT AS DATE;
        DECLARE @LS_KHONG_KH AS NUMERIC(10,2);

        -- Gán giá trị cho các biến
        SET @NGAYGUI = (SELECT NGAY_GUI FROM TIENGUI_TIETKIEM WHERE MA_TAIKHOAN_TIETKIEM = @MA_TAIKHOAN);
        SET @NGAYDENHAN = (SELECT NGAY_DENHAN FROM TIENGUI_TIETKIEM WHERE MA_TAIKHOAN_TIETKIEM = @MA_TAIKHOAN);
        SET @TUGIAHAN = (SELECT TUGIAHAN FROM TIENGUI_TIETKIEM WHERE MA_TAIKHOAN_TIETKIEM = @MA_TAIKHOAN);
        SET @NGAYRUT = (SELECT NGAY_RUT FROM TIENGUI_TIETKIEM WHERE MA_TAIKHOAN_TIETKIEM = @MA_TAIKHOAN);
        SET @LS_KHONG_KH = (SELECT CASE LOAITIEN WHEN 'VND' THEN 0.1 ELSE 0 END FROM TIENGUI_TIETKIEM WHERE MA_TAIKHOAN_TIETKIEM = @MA_TAIKHOAN);

        -- Phân chia các trường hợp
        -- TH1: RÚT TIỀN TRƯỚC HẠN
        IF @NGAYRUT < @NGAYDENHAN
        BEGIN
            -- Tính lãi không kỳ hạn
            UPDATE TIENGUI_TIETKIEM
            SET SOTIEN_LAI = (DATEDIFF(D, @NGAYGUI, @NGAYRUT) * 0.1 * SOTIEN) / (100 * 365)
            WHERE MA_TAIKHOAN_TIETKIEM = @MA_TAIKHOAN;
        END
        ELSE
        BEGIN
            -- TH2: RÚT TIỀN SAU HẠN, xử lý gia hạn
            IF @TUGIAHAN = 1
            BEGIN
                -- Gọi PROC XOAY VÒNG
                EXEC XOAYVONG2 @MA_TAIKHOAN;
                
                -- Cập nhật lãi suất không kỳ hạn cho những ngày còn lại
                UPDATE TIENGUI_TIETKIEM
                SET SOTIEN_LAI = SOTIEN_LAI + (DATEDIFF(D, NGAY_GUI, @NGAYRUT) * @LS_KHONG_KH * SOTIEN) / (100 * 365)
                WHERE MA_TAIKHOAN_TIETKIEM = @MA_TAIKHOAN;
            END
            ELSE
            BEGIN
                -- Tính lãi 1 kỳ gửi, và tính lãi suất không kỳ hạn cho những ngày còn lại
                UPDATE TIENGUI_TIETKIEM
                SET SOTIEN_LAI = (DATEDIFF(D, @NGAYGUI, @NGAYDENHAN) * LAISUAT * SOTIEN) / (100 * 365) -- Lãi 1 kỳ
                    + (DATEDIFF(D, @NGAYDENHAN, @NGAYRUT) * @LS_KHONG_KH * SOTIEN) / (100 * 365) -- Lãi không kỳ hạn
                WHERE MA_TAIKHOAN_TIETKIEM = @MA_TAIKHOAN;
            END;
        END;

        -- Lấy tài khoản tiếp theo
        FETCH NEXT FROM CURSOR_TAIKHOAN INTO @MA_TAIKHOAN;
    END;

    -- Đóng CURSOR
    CLOSE CURSOR_TAIKHOAN;
    DEALLOCATE CURSOR_TAIKHOAN;
END;

-- THỰC THI
EXEC TINHLAI_TIENGUI_TIETKIEM;
