--- TẠO BẢNG TẠM CHỨA DANH SÁCH KHÁCH HÀNG KÈM NHÓM NỢ (SỐ LỚN NHẤT) VÀ CHI NHÁNH
CREATE TABLE BANG_TAM (
    MA_HOPDONG_TINDUNG NVARCHAR(20),
    KYTRA INT,
    NGAY_CUOIKY DATE,
    NGAYTRA DATE,
    SOTIEN_GOC NUMERIC(18, 2),
    SOTIEN_LAI NUMERIC(18, 0),
    TONG_TIEN NUMERIC(18, 0),
    NHOM_NO INT,
    MA_KHACHHANG NVARCHAR(20),
    MA_CHINHANH NVARCHAR(20),
    TEN_CHINHANH NVARCHAR(100),
    ROW_NUM INT
);

--- CẬP NHẬT DỮ LIỆU CHO BẢNG TẠM DANH SÁCH KHÁCH HÀNG KÈM NHÓM NỢ (SỐ LỚN NHẤT) VÀ CHI NHÁNH
WITH CTE AS (
    SELECT A.MA_HOPDONG_TINDUNG,
           A.KYTRA,
           A.NGAY_CUOIKY,
           ISNULL(B.NGAYTRA, '9999-12-31') AS NGAYTRA,
           A.SOTIEN_GOC,
           A.SOTIEN_LAI,
           A.TONG_TIEN,
           CASE 
               WHEN (DATEDIFF(D, NGAY_CUOIKY, NGAYTRA) + 1) < 10 THEN 1
               WHEN (DATEDIFF(D, NGAY_CUOIKY, NGAYTRA) + 1) BETWEEN 10 AND 90 THEN 2
               WHEN (DATEDIFF(D, NGAY_CUOIKY, NGAYTRA) + 1) BETWEEN 91 AND 180 THEN 3
               WHEN (DATEDIFF(D, NGAY_CUOIKY, NGAYTRA) + 1) BETWEEN 181 AND 360 THEN 4
               ELSE 5
           END AS NHOM_NO
    FROM KEHOACH_TRANO A
    LEFT JOIN KHACHHANG_TRANO B
        ON A.MA_HOPDONG_TINDUNG = B.MA_HOPDONG_TINDUNG AND A.KYTRA = B.KYTRA
)
, CTE_RANKED AS (
    SELECT B.MA_KHACHHANG, 
           CTE.*, 
           C.MA_CHINHANH, 
           C.TEN_CHINHANH,
           ROW_NUMBER() OVER (PARTITION BY CTE.MA_HOPDONG_TINDUNG ORDER BY CTE.NHOM_NO DESC) AS ROW_NUM
    FROM CTE
    INNER JOIN HOPDONG_TINDUNG A 
        ON CTE.MA_HOPDONG_TINDUNG = A.MA_HOPDONG_TINDUNG
    INNER JOIN KHACHHANG B 
        ON B.MA_KHACHHANG = A.MA_KHACHHANG
    INNER JOIN CHINHANH C 
        ON C.MA_CHINHANH = B.MA_CHINHANH
)
INSERT INTO BANG_TAM (
    MA_HOPDONG_TINDUNG,
    KYTRA,
    NGAY_CUOIKY,
    NGAYTRA,
    SOTIEN_GOC,
    SOTIEN_LAI,
    TONG_TIEN,
    NHOM_NO,
    MA_KHACHHANG,
    MA_CHINHANH,
    TEN_CHINHANH,
    ROW_NUM
)
SELECT 
    MA_HOPDONG_TINDUNG,
    KYTRA,
    NGAY_CUOIKY,
    NGAYTRA,
    SOTIEN_GOC,
    SOTIEN_LAI,
    TONG_TIEN,
    NHOM_NO,
    MA_KHACHHANG,
    MA_CHINHANH,
    TEN_CHINHANH,
    ROW_NUM
FROM CTE_RANKED
WHERE ROW_NUM = 1
ORDER BY MA_HOPDONG_TINDUNG, KYTRA;
---
SELECT * FROM BANG_TAM
ORDER BY MA_CHINHANH, NHOM_NO;

--- PROC NHẬP VÀO MÃ KHÁCH HÀNG -> IN RA NHÓM NỢ CỦA KHÁCH HÀNG; DANH SÁCH SỐ LƯỢNG KHÁCH HÀNG THEO NHÓM NỢ CỦA CHI NHÁNH
ALTER PROC KHACHHANG_NHOMNO
@MAKHACHHANG NVARCHAR(50)
AS
BEGIN
    -- Truy vấn danh sách số lượng khách hàng theo nhóm nợ của chi nhánh @MACHINHANH
    SELECT @MAKHACHHANG AS MA_KHACHHANG, NHOM_NO
    FROM BANG_TAM
    WHERE MA_KHACHHANG = @MAKHACHHANG;
END;

--- THỰC THI
EXEC KHACHHANG_NHOMNO 'CIF0006599';
