CREATE PROCEDURE BC_THUCHI
    @StartDate DATE,
    @EndDate DATE
AS
BEGIN
    -- TẠO BẢNG BAOCAO_THUCHI NẾU CHƯA TỒN TẠI
    IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'BAOCAO_THUCHI')
    BEGIN
        CREATE TABLE BAOCAO_THUCHI (
            ID  INT PRIMARY KEY,
            TIEU_CHI  NVARCHAR(500),
            SO_TIEN  NUMERIC(18,2)
        );

        INSERT INTO BAOCAO_THUCHI (ID, TIEU_CHI, SO_TIEN)
        VALUES (1, N'DOANH THU TỪ LÃI CÁC HĐTD', 0),
               (2, N'CHI PHÍ LÃI TIỀN GỬI KHÔNG KỲ HẠN', 0),
               (3, N'CHI PHÍ LÃI TIỀN GỬI CÓ KỲ HẠN', 0),
               (4, N'CHI PHÍ LÃI TIỀN GỬI TIẾT KIỆM', 0),
               (5, N'TỔNG LỢI NHUẬN', 0);
    END;

    -- CẬP NHẬT DÒNG DOANH THU TỪ LÃI CÁC HĐTD
    UPDATE BAOCAO_THUCHI
    SET SO_TIEN = ISNULL(
        (SELECT SUM(SOTIEN_LAI)
        FROM KHACHHANG_TRANO
        WHERE NGAYTRA >= @StartDate AND NGAYTRA <= @EndDate)
    ,0)
    WHERE ID = 1;

    -- CẬP NHẬT CHI PHÍ LÃI TIỀN GỬI KHÔNG KỲ HẠN
    EXEC THEM_SODUCUOINGAY @StartDate, @EndDate;
    
    UPDATE BAOCAO_THUCHI
    SET SO_TIEN = ISNULL(
        (SELECT SUM(SODUCUOINGAY) * 0.1 / 100 / 365
        FROM TINH_SODUCUOINGAY
        WHERE NGAY_GIAODICH >= @StartDate AND NGAY_GIAODICH <= @EndDate)
    ,0)
    WHERE ID = 2;

    -- CẬP NHẬT CHI PHÍ LÃI TIỀN GỬI CÓ KỲ HẠN
    UPDATE BAOCAO_THUCHI
    SET SO_TIEN = ISNULL(
        (SELECT SUM(SOTIEN_LAI)
        FROM TIENGUI_COKYHAN
        WHERE NGAY_RUT >= @StartDate AND NGAY_RUT <= @EndDate)
    ,0)
    WHERE ID = 3;

    -- CẬP NHẬT CHI PHÍ LÃI TIỀN GỬI TIẾT KIỆM
    UPDATE BAOCAO_THUCHI
    SET SO_TIEN = ISNULL(
        (SELECT SUM(SOTIEN_LAI)
        FROM TIENGUI_TIETKIEM
        WHERE NGAY_RUT >= @StartDate AND NGAY_RUT <= @EndDate)
    ,0)
    WHERE ID = 4;

    -- LƯU TẠM DỮ LIỆU VÀ TÍNH TỔNG LỢI NHUẬN
    DECLARE @DOANH_THU NUMERIC(18,2),
            @CHI_PHI_KKH NUMERIC(18,2),
            @CHI_PHI_COKH NUMERIC(18,2),
            @CHI_PHI_TIETKIEM NUMERIC(18,2);

    -- LẤY DỮ LIỆU TỪ BẢNG BAOCAO_THUCHI
    SELECT @DOANH_THU = SO_TIEN FROM BAOCAO_THUCHI WHERE ID = 1;
    SELECT @CHI_PHI_KKH = SO_TIEN FROM BAOCAO_THUCHI WHERE ID = 2;
    SELECT @CHI_PHI_COKH = SO_TIEN FROM BAOCAO_THUCHI WHERE ID = 3;
    SELECT @CHI_PHI_TIETKIEM = SO_TIEN FROM BAOCAO_THUCHI WHERE ID = 4;

    -- CẬP NHẬT DÒNG TỔNG LỢI NHUẬN UPDATE BAOCAO_THUCHI
	UPDATE BAOCAO_THUCHI
	SET SO_TIEN = @DOANH_THU - @CHI_PHI_KKH - @CHI_PHI_COKH - @CHI_PHI_TIETKIEM
	WHERE ID = 5;
END;

-- THỰC THI
EXEC BC_THUCHI @StartDate = '2024-02-01', @EndDate = '2024-02-29';

SELECT * FROM BAOCAO_THUCHI;
