UPDATE TIENGUI_TIETKIEM
SET NGAY_GUI = '2024-03-26', NGAY_DENHAN = '2025-04-09'
WHERE MA_TAIKHOAN_TIETKIEM = 'CSAV0015213.1' AND NGAY_RUT = '2024-07-09';

UPDATE HOPDONG_THECHAP
SET NGAY_HOPDONG_THECHAP = B.NGAY_HD
FROM 
HOPDONG_THECHAP A
INNER JOIN (
    SELECT MA_HOPDONG_THECHAP, MIN(NGAY_GIAINGAN) AS 'NGAY_HD'
    FROM HOPDONG_TINDUNG
    GROUP BY MA_HOPDONG_THECHAP
) B 
ON A.MA_HOPDONG_THECHAP = B.MA_HOPDONG_THECHAP;
